### ISSUE TITLE
Questions about Pydantic and Unicode symbols

### ISSUE THREAD

**Issue by martinkozle** [kalaspuff/stockholm#270]
Hello, first of all, I want to say thanks for the great library! It is very well explained with a lot of examples and it is very feature rich.
I have 2 questions and I couldn't find a wiki or a discord or any other discussion forum so I guess I will open an issue to ask.

First is what is the most intended way to use this library with Pydantic 2?
It would have been cool if the Money object was a Pydantic BaseModel or supported Pydantic schemas for serialization, but since that is not the case am I supposed to convert it to a dict, parse it as a Pydantic model and store it like that? And then when I want to do money operations I am supposed to convert it back and forth?
Or is working with Pydantic models just not a considered aspect of this library? If you are interested I could try to contribute this functionality.

My second question is does this library support formatting money using Unicode symbols?
For example: €5.00, -€4.21, $50, -$7
And is this a feature that you are interested in getting a contribution for?

**Comment by kalaspuff** [comment]
:wave: Thank you. Nice to see the wish for this functionality already. 🙏  

Actually started adding support for the Money objects to work together with Pydantic model last week. The path so far is not to incur an additional dependency on Pydantic itself, but to make it compatible with Pydantic by adding the `__get_pydantic_core_schema__` classmethod. It exposes how the object converts back and forth and validates according to JSON schemas, which will make it fully supported to be included in Pydantic models. Basically by adding the schema to make Pydantic accept the `Money`, `Number` and `Currency` objects / types as valid input for models inheriting `pydantic.BaseModel`. The solution is going to be built and tested primarily to work with Pydantic 2.

Will most likely get it out next week and will loop back to this issue when it's out — will help workflows where we want to use the Money objects together with Pydantic in a better way.

---

Regarding currency symbols I've previously haven't added these, mainly due to the use of ISO 4217 currency codes mainly in backend systems and in application-to-application transport layers such as in protobuf or JSON where the symbols make little sense themself. Paritally due to the issues with some symbols being ambiguous (e.g. $ is used for USD, CAD, AUD, etc.), that's also mentioend as a tricky thing to battle in [unicode's docs around currency names and symbols](https://cldr.unicode.org/translation/currency-names-and-symbols#h.l74rsgppoqzg). 

However, I'm open that this can be added as an option, for wherever these values may be used in user facing applications.

**Comment by kalaspuff** [comment]
Support to use `Money` objects within Pydantic models is now released as part of the [0.5.7](https://github.com/kalaspuff/stockholm/releases/tag/0.5.7) `stockholm` release. 🎉

**Comment by martinkozle** [comment]
Thanks for the feature! As for the second part of this issue I ended up using babel for the Unicode symbol formatting. I am closing this issue now.
